import { Product } from "./Product";

export const products: Product[] = [
  {
    id: 1,
    name: "Alerdog",
    description: "Tratamiento en los Síntomas de las Dermatitis Alérgicas Control del Prurito e Inflamación Dérmica",
    image: "500_ALER.png",
    category: "Perro",
  },
  {
    id: 2,
    name: "Alivet",
    description: "SHAMPOO MEDICADO ANTIPARASITARIO Y ANTISEBORREICO",
    image: "500_ALI.png",
    category: "Perro"
  },
  {
    id: 3,
    name: "Micodermal",
    description: "-Infecciones Bacterianas y Fúngicas Forunculosis Impétigo Seborreas Infecciosas",
    image: "500_MICO.png",
    category: "Perro",
  },
  {
    id: 4,
    name: "Natudermal",
    description: "UNA DE GATO SANGRE DE GRADO ACEITE DE COPAIBA LLANTEN TILO",
    image: "500_NATU.png",
    category: "Perro"
  },
  {
    id: 5,
    name: "Sanidermal",
    description: "- Trastorno de Cornificación y Queratinización Desórdenes Descamativos en Seborreas e Ictiosis",
    image: "500_SANI.png",
    category: "Perro",
  }, 
  {
    id: 6,
    name: "Triplea",
    description: "-Queratolítico Queratoplástico Desengrasante Antiseborreico",
    image: "500_TRI.png",
    category: "Perro",
  },
  {
    id: 7,
    name: "Avena + Glicerina",
    description: "(Neutro: Alergias y Piel Delicada: Especial para Cachorritos",
    image: "2000x2000_AVENA_500.png",
    category: "Perro"
  },
  {
    id: 8,
    name: "AVENA + GLICERINA ESPUMA",
    description: "SHAMPOO HIPOALERGÉNICO",
    image: "2000x2000_AVENA.png",
    category: "Perro",
  },
    {
    id: 9,
    name: "Laperm",
    description: "En baño seco espuma",
    image: "2000x2000_LAPERM.png",
    category: "Gato",
  },
  {
    id: 10,
    name: "Menta Citronella",
    description: "Antipulgas y Garrapatas",
    image: "2000x2000_MENTA_500.png",
    category: "Perro",
  },
  {
    id: 11,
    name: "Artriflex",
    description: "Antiinflamatorio Natural Osteoarticular Condroprotecto Regenerador",
    image: "ARTRI.jpg",
    category: "Perro",
  },
  {
    id: 12,
    name: "Artriflex Caja",
    description: "Antiinflamatorio Natural Osteoarticular Condroprotecto Regenerador",
    image: "ARTRIFLEX_CAJA.png",
    category: "Perro",
  },
  {
    id: 13,
    name: "Avena Glicerina",
    description: "CH Neutro; Alergias. y Piel Delicada: Especial para Cachorritos",
    image: "Avena+Glicerina.png",
    category: "Perro",
  },
  {
    id: 14,
    name: "Caja Gato Lista",
    description: "Shampoo paraGatos con Aloe Vera y Extracto de Avena",
    image: "CAJA_GATO_LISTA.jpg",
    category: "Gato",
  },
    {
    id: 15,
    name: "CANIDEX CAJA",
    description: "ANTIINFLAMATORIO ESTEROIDEO DEXAMETAZONA ACETATO",
    image: "CANIDEX_CAJA.png",
    category: "Gato",
  },
  {
    id: 16,
    name: "CANIVET TAB CAJA",
    description: "ANTIPARASITARIO DE AMPLIO ESPECTRO",
    image: "CANIVET_TAB_CAJA.png",
    category: "Gato",
  },
  {
    id: 17,
    name: "CEFADOG 300 CAJA",
    description: "ANTIBIÓTICO BETALACTÁMICO CEFALEXINA CON SILIMARINA",
    image: "CEFADOG_300_CAJA.png",
    category: "Perro",
  },
    {
    id: 18,
    name: "CEFADOG_600_CAJA",
    description: "ANTIBIOTICO BETALACTÁMICO CEFALEXINA CON SILIMARINA",
    image: "CEFADOG_600_CAJA.png",
    category: "Perro",
  },
  {
    id: 19,
    name: "CEFADOG NEW",
    description: "ANTIBIÓTICO BETALACTÁMICO CEFALEXINA CON SILIMARINA",
    image: "CEFADOG_NEW.jpg",
    category: "Perro",
  },
  {
    id: 20,
    name: "CLAMOX 5 CAJA",
    description: "ANTIBIÓTICO BETALACTÁMICO CEFALEXINA CON SILIMARINA",
    image: "CLAMOX_5_CAJA.png",
    category: "Perro",
  },
  {
    id: 21,
    name: "CLAMOXPET_CAJA",
    description: "ANTIBIÓTICO DE AMPLIO ESPECTRO ÁCIDO CLAVULANICO 50 mg AMOXICILINA 200mg",
    image: "CLAMOXPET_CAJA.png",
    category: "Perro",
  },
  {
    id: 22,
    name: "CLINDAPET CAJA",
    description: "ANTIBIÓTICO AMPLIO ESPECTRO CLINDAMICINA 150 mg",
    image: "CLINDAPET_CAJA.png",
    category: "Perro",
  },
    {
    id: 23,
    name: "CORTIVET_CAJA",
    description: "ANTIINFLAMATORIO Y ANTIALERGICO 40 PREDNISONA 20 mg",
    image: "CORTIVET_CAJA.png",
    category: "Perro",
  },
  {
    id: 24,
    name: "DERMATAB 10 CAJA",
    description: "INFECCIONES DERMATOLÓGICAS 30 CEFALEXINA + SULFATO DE ZINC + BIOTINA",
    image: "DERMATAB_10_CAJA.png",
    category: "Perro",
  },
    {
    id: 25,
    name: "DERMATAB 20 CAJA",
    description: "INFECCIONES DERMATOLÓGICAS 30 CEFALEXINA + SULFATO DE ZINC + BIOTINA",
    image: "DERMATAB_20_CAJA.png",
    category: "Perro",
  },
  {
    id: 26,
    name: "DESPARASIT CAJA",
    description: "ANTIPARASITARIO DE AMPLIO ESPECTRO 30 FEBENDAZOL + PRAZICUANTE + PAMOATO DE PIRANTEL",
    image: "DESPARASIT_CAJA.png",
    category: "Perro",
  },
    {
    id: 27,
    name: "DOLORDOG 44 CAJA",
    description: "ANTINFLAMATORIO NO ESTEROIDEO CARPROFENO 44 mg",
    image: "DOLORDOG_44_CAJA.png",
    category: "Perro",
  },
  {
    id: 28,
    name: "DOLORDOG 88 CAJA",
    description: "ANTINFLAMATORIO NO ESTEROIDEO CARPROFENO 44 mg",
    image: "DOLORDOG_88_CAJA.png",
    category: "Perro",
  },
    {
    id: 29,
    name: "DOXIDOG 50 CAJA",
    description: "ANTIBIOTICO DE AMPLIO ESPECTRO 30 DOXICICLINA 50 mg",
    image: "DOXIDOG_50_CAJA.png",
    category: "Perro",
  },
  {
    id: 30,
    name: "DOXIDOG 200 CAJA",
    description: "ANTIBIOTICO DE AMPLIO ESPECTRO 30 DOXICICLINA 50 mg",
    image: "DOXIDOG_200_CAJA.png",
    category: "Perro",
  },
  {
    id: 31,
    name: "ENROTAB 50 CAJA",
    description: "ANTIBIÓTICO DE AMPLIO ESPECTRO ENROFLOXACINA 50 mg",
    image: "ENROTAB_50_CAJA.png",
    category: "Perro",
  },
    {
    id: 32,
    name: "ENROTAB 150 CAJA",
    description: "ANTIBIÓTICO DE AMPLIO ESPECTRO ENROFLOXACINA 50 mg",
    image: "ENROTAB_150_CAJA.png",
    category: "Perro",
  },
  {
    id: 33,
    name: "Fiprocan Forte",
    description: "GARRAPATAS ÁCAROS y PULGAS",
    image: "Fiprocan_Forte.png",
    category: "Perro",
  },
  {
    id: 34,
    name: "FIPROLER 1",
    description: "Contra GARRAPATAS y PULGAS",
    image: "FIPROLER_1.jpg",
    category: "Perro",
  },
  {
    id: 35,
    name: "FIPROLER_2",
    description: "Contra GARRAPATAS y PULGAS",
    image: "FIPROLER_2.jpg",
    category: "Perro",
  },
  {
    id: 36,
    name: "FIPROLER_3",
    description: "Contra GARRAPATAS y PULGAS",
    image: "FIPROLER_3.jpg",
    category: "Perro",
  },
  {
    id: 37,
    name: "FIPROLER_4",
    description: "Contra GARRAPATAS y PULGAS",
    image: "FIPROLER_4.jpg",
    category: "Perro",
  },
    {
    id: 38,
    name: "Fiproler Spray",
    description: "Contra GARRAPATAS y PULGAS",
    image: "Fiproler_Spray.jpg",
    category: "Perro",
  },
  {
    id: 39,
    name: "Firpocan Forte",
    description: "Contra GARRAPATAS ÁCAROS y PULGAS",
    image: "firpocan_forte.jpg",
    category: "Perro",
  },
  {
    id: 40,
    name: "GAL LITRO 2EN1",
    description: "Para un pelaje Limpio, Brilloso, Suave y Bello",
    image: "GAL_LITRO_2EN1.jpg",
    category: "Perro",
  },
      {
    id: 42,
    name: "GAL LITRO ACONDICIONADOR",
    description: "Para un pelaje Limpio, Brilloso, Suave y Bello",
    image: "GAL_LITRO_ACONDICIONADOR.jpg",
    category: "Perro",
  },
  {
    id: 43,
    name: "GAL LITRO ALERDOG",
    description: "Tratamiento en los Síntomas de la Dermatitis Alérgica Control del Prurito e Inflamación Dérmica",
    image: "GAL_LITRO_ALERDOG.jpg",
    category: "Perro",
  },
   {
    id: 44,
    name: "GAL LITRO ALIVET",
    description: "Shampoo Medicado Antiparasitario y Antiseborreico",
    image: "GAL_LITRO_ALERDOG.jpg",
    category: "Perro",
  },
  {
    id: 45,
    name: "GAL_LITRO_AVENA",
    description: "PH Neutro, Alergias, Piel Delicada; Especial para Cachorritos",
    image: "GAL_LITRO_AVENA.jpg",
    category: "Perro",
  },
   {
    id: 46,
    name: "GAL_LITRO_CLOR",
    description: "Infectiones Bacterianas, Manchas Calientes y Seborreas Infecciosas",
    image: "GAL_LITRO_CLOR.jpg",
    category: "Perro",
  },
  {
    id: 47,
    name: "GAL LITRO CLOR + CLO",
    description: "Infecciones Bacterianas, Antimicóticos, Furunculosis, Manchas Calientes, Impétigo ySeborreas Infecciosas",
    image: "GAL_LITRO_CLOR+CLO.jpg",
    category: "Perro",
  },
  {
    id: 48,
    name: "GAL_LITRO_DERMASAN",
    description: "Problemas Dermatológicos, Queratolítico, Antieczemático, Microbicida y Antimicótico",
    image: "GAL_LITRO_DERMASAN.jpg",
    category: "Perro",
  },
    {
    id: 49,
    name: "GAL LITRO FIPROLER_SPRAY",
    description: "Solución cutánea de uso externo contra Pulgas, Garrapatas y Acaros de acción prolongada extrema USO EXCLUSIVO PARA PERROS",
    image: "GAL_LITRO_FIPROLER_SPRAY.jpg",
    category: "Perro",
  },
  {
    id: 51,
    name: "GAL LITRO HIPOCLOROSO",
    description: "DESINFECTANTE CICATRIZANTE DE HERIDAS SOLUCIÓN TÓPICA BIOCIDA, BACTERIANA, VIRICIDA Y FUNGICIDA",
    image: "GAL_LITRO_HIPOCLOROSO.jpg",
    category: "Perro",
  },
    {
    id: 52,
    name: "GAL_LITRO_KETOCONAZOL",
    description: "Infecciones Fúngicas, Dermatofitosis, Forunculosis y Manchas Calientes",
    image: "GAL_LITRO_KETOCONAZOL.jpg",
    category: "Perro",
  },
      {
    id: 53,
    name: "GAL_LITRO_MENTA_CITRONELLA",
    description: "Antipulgas y Garrapatas",
    image: "GAL_LITRO_MENTA_CITRONELLA.jpg",
    category: "Perro",
  },
  {
    id: 54,
    name: "GAL LITRO MICODERMAL",
    description: "Infecciones Bacterianas y Fúngicas, Forunculosis, Impétigo y Seborreas Infecciosas",
    image: "GAL_LITRO_MICODERMAL.jpg",
    category: "Perro",
  },
    {
    id: 55,
    name: "GAL LITRO NATUDERMAL",
    description: "Cicatrizante, Microbicida, Coadyuvante en Dermatitis, Previene Infecciones",
    image: "GAL_LITRO_NATUDERMAL.jpg",
    category: "Perro",
  },
  {
    id: 56,
    name: "GAL LITRO NATUDERMAL",
    description: "Cicatrizante, Microbicida, Coadyuvante en Dermatitis, Previene Infecciones",
    image: "GAL_LITRO_NATUDERMAL.jpg",
    category: "Perro",
  },
   {
    id: 57,
    name: "GAL LITRO SANIDERMAL",
    description: "Transtorno de Cornificación y Queratinización, Desordenes Descamativos en Seborreas e Ictiosis",
    image: "GAL_LITRO_SANIDERMAL.jpg",
    category: "Perro",
  },
  {
    id: 58,
    name: "GAL LITRO SARNA",
    description: "Antisárnico Contra Garrapatas",
    image: "GAL_LITRO_SARNA.jpg",
    category: "Perro",
  },
    {
    id: 59,
    name: "GAL_LITRO_TRIPLE_A",
    description: "Infecciones Seborreicas causadas por bacterias y hongos con actividad queratolítica, queratoplástica;, Desengrasante y Antimicrobiano",
    image: "GAL_LITRO_TRIPLE_A.jpg",
    category: "Perro",
  },
  {
    id: 60,
    name: "GAL LITRO VETLINEX",
    description: "Higiene General, Queratolico, Antieczemático, Microbicida, Antisárnico y Antisehorreico",
    image: "GAL_LITRO_VETLINEX.jpg",
    category: "Perro",
  },
    {
    id: 61,
    name: "GAL_LITRO_VITALDERM",
    description: "Antipulgas",
    image: "GAL_LITRO_VITALDERM.jpg",
    category: "Perro",
  },
  {
    id: 62,
    name: "GIARDIAPET A CAJA",
    description: "COCCIDICIDA - GIARDICIDA - ANTIBACTERIANO",
    image: "GIARDIAPET_A_CAJA.png",
    category: "Perro",
  },
  {
    id: 63,
    name: "GIARDIAPET R CAJA",
    description: "COCCIDICIDA - GIARDICIDA - ANTIBACTERIANO",
    image: "GIARDIAPET_R_CAJA.png",
    category: "Perro",
  },
    {
    id: 64,
    name: "GIARDIAPET V CAJA",
    description: "COCCIDICIDA - GIARDICIDA - ANTIBACTERIANO",
    image: "GIARDIAPET_V_CAJA.png",
    category: "Perro",
  },
      {
    id: 65,
    name: "Gingivet frasco caja",
    description: "COCCIDICIDA - GIARDICIDA - ANTIBACTERIANO",
    image: "Gingivet_frasco_caja.jpg",
    category: "Perro",
  },
  {
    id: 66,
    name: "GRISEOVET_CAJA",
    description: "ANTIMICÓTICO DERMATOMICOSISY ONICOMICOSIS",
    image: "GRISEOVET_CAJA.png",
    category: "Perro",
  },
   {
    id: 67,
    name: "HEMOVITAB_CAJA",
    description: "SUPLEMENTO NUTRICIONAL ANTIANEMICO",
    image: "HEMOVITAB_CAJA.png",
    category: "Perro",
  },
  {
    id: 68,
    name: "Hepa 02",
    description: "HEPATOPROTECTOR Y ANTIOXIDANTE",
    image: "Hepa_02.jpg",
    category: "Perro",
  },
    {
    id: 69,
    name: "HEPABIOT_TAB_CAJA",
    description: "Hepatoprotector Desintoxicante",
    image: "HEPABIOT_TAB_CAJA.png",
    category: "Perro",
  },
  {
    id: 70,
    name: "Hipocloroso 500 ml",
    description: "SPRAY DESINFECTANTE Y CICATRIZANTE DE HERIDAS",
    image: "Hipocloroso_500_ml.jpg",
    category: "Perro",
  },
    {
    id: 71,
    name: "Hipocloroso Spray Trans",
    description: "SPRAY DESINFECTANTE Y CICATRIZANIE DE HERIDAS",
    image: "Hipocloroso_Spray_Trans.png",
    category: "Perro",
  },
     {
    id: 72,
    name: "HOYNO 1",
    description: "EVITA LA MOLESTIA DE MACHOS NO DESEADOS",
    image: "HOYNO_1 - copia.jpg",
    category: "Perro",
  },
  {
    id: 73,
    name: "INMUNAT_CAJA",
    description: "Apoyo en la Función Inmunológica",
    image: "INMUNAT_CAJA.png",
    category: "Perro",
  },
    {
    id: 74,
    name: "KETOPROPET 5 CAJA",
    description: "ANALGESICO Y ANTINFLAMATORIO",
    image: "KETOPROPET_5_CAJA.png",
    category: "Perro",
  },
  {
    id: 75,
    name: "KETOPROPET 20 CAJA",
    description: "ANALGESICO Y ANTINFLAMATORIO",
    image: "KETOPROPET_20_CAJA.png",
    category: "Perro",
  },
  {
    id: 76,
    name: "LOCION 2",
    description: "Locion",
    image: "LOCION_2.jpg",
    category: "Perro",
  },
    {
    id: 77,
    name: "OMEPRADOG_CAJA",
    description: "ANTIULCEROSO GÁSTRICO",
    image: "OMEPRADOG_CAJA.png",
    category: "Perro",
  },
  {
    id: 78,
    name: "ONCONAT CAJA",
    description: "Disminuye el Crecimiento de las Células Neoplásicas",
    image: "ONCONAT_CAJA.png",
    category: "Perro",
  },
    {
    id: 80,
    name: "Oticlean 260",
    description: "Limpiador Ótico",
    image: "ONCONAT_CAJA.png",
    category: "Perro",
  },
    {
    id: 81,
    name: "Pipi Can",
    description: "Educador de Cachorros",
    image: "Pipi_Can.jpg",
    category: "Perro",
  },
    {
    id: 82,
    name: "SUPERTAB_CAJA",
    description: "Suplemento Alimenticio para Perros",
    image: "SUPERTAB_CAJA.png",
    category: "Perro",
  },
      {
    id: 83,
    name: "URONAT_CAJA",
    description: "Coadyuvante en Enfermedades Renales",
    image: "URONAT_CAJA.png",
    category: "Perro",
  },
  {
    id: 84,
    name: "Vitalderm",
    description: "Efectivo con las Pulgas",
    image: "Vitalderm.png",
    category: "Perro",
  },
  
  

























]